assigness: []
harvest_options:
  path: s3://ooi-data
  refresh: true
  test: false
instrument: CE06ISSP-SP001-02-DOSTAJ000
stream:
  method: telemetered
  name: dosta_abcdjm_cspp_instrument
workflow_config:
  schedule: 0 0 * * *
